### ISSUE TITLE
Physical properties of the simulated model requires checking

### ISSUE THREAD

**Issue by adam-slucki** [tooploox/car_robot#2] opened 2021-04-10 09:51 UTC
As the model behaves strangely in simulation I guess there's something wrong with its description and/or physical properties defined in URDF (`collision`, `inertia`, and `joints` tags in general should be checked).

Potentially helpful resources: http://gazebosim.org/tutorials/?tut=ros_urdf

It should make more sense to resolve #1 first.

**Comment by piotr-marcol-tpx** [comment] 2021-05-19 11:00
Branch: https://github.com/tooploox/autonomous_car_model/tree/002_physical_properties_of_the_simulated_model_requires_checking

**Found issues:**

1. (**Solved**) In gazebo, model is dropped from some height instead of being spawned right on the ground
![car_drop_cut](https://user-images.githubusercontent.com/72254059/118802149-14510980-b8a2-11eb-8c08-daa223810c85.gif)

2. (**Ignorable**) Left wheels are somewhat more outside of the body than right ones. Not sure whether this may affect physics, but if that's an easy to track and fix issue (and I suppose it is), then it'd probably be worth looking into.
![image](https://user-images.githubusercontent.com/72254059/118803228-63e40500-b8a3-11eb-93ab-71a56e2d36b2.png)

3. (**Solved**) After adding the camera model car inertia is tilted to the right (I'm not sure if it causes any problems though).

4. Contact with the ground is not constant (it flickers for at least two wheels), not sure what causes this behaviour and how problematic it is.

5. (**Solved**) Lidar laser and mesh used for visualization are not aligned.

6. Wheels are slowly rotating. What is interesting - front wheel revolute forwards, while rear wheels - backwards.
![image](https://user-images.githubusercontent.com/72254059/118938143-9dbe1580-b94e-11eb-8dc2-59d042c8b184.png)
The rotation is very slow, actually optically hardly noticeable. I only noticed it accidentally while messing around in gazebo - attribute `angle_0` was constantly changing a little bit over time.
**Note:** this strange behaviour of `angle_0` attribute can be observed for (almost?) all joints actually.

7. (**Solved**) Body inertia is skewed; in urdf everything seems to be ok, but somehow in gazebo it is visualized like that:
![image](https://user-images.githubusercontent.com/72254059/118972013-5e082580-b970-11eb-9aec-62ba8003aa43.png)

**Comment by adam-slucki** [comment] 2021-05-19 11:35
I can add:
3. After adding the camera model car inertia is tilted to the right (I'm not sure if it causes any problems though).
4. Contact with the ground is not constant (it flickers for at least two wheels), not sure what causes this behaviour and how problematic it is.
5. Lidar laser and mesh used for visualization are not aligned.

**Comment by piotr-marcol-tpx** [comment] 2021-05-19 13:44
Update:

ad 1. spawning the car too high was caused by the too high value of argument `x` in  `car_gazebo.launch` file; was `1.0`, changed to `0.0325` (i.e. `wheel_radius`) in 6dc02c86a50a5f574e7e866395742c9c5f5f584f.

**Comment by piotr-marcol-tpx** [comment] 2021-06-09 11:02
Update:

ad 3. and 7.: the tilt was caused by parameter `d435i_cam_depth_py`; it is responsible for offset of the camera (in terms of joint to base_link placement, visualization and collision) along the Y axis. The initial value was 0.0175, which caused the mass not to be symmetrically distributed. Changing the value to 0 fixed it. (commit 26a4e4b)

**Comment by piotr-marcol-tpx** [comment] 2021-06-09 11:48
Update:

ad 2. After further inspection, it is more of a visualization issue and should not affect physical properties of the model; the collisions and inertias seem to be symmetrical.

**Comment by piotr-marcol-tpx** [comment] 2021-06-17 11:25
ad 5. Fixed in f3343d9.

**Closed as completed** 2021-06-18 05:59 UTC
Labels: bug, good first issue, high priority
